project:
  type: website
  output-dir: docs
website:
  title: "open room"
  site-url: https://tonyderrico.github.io/blog/
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/tonyderrico
      - icon: twitter
        href: https://x.com/tony_derr
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

